// frontend/vue-sample/src/components/common/PostForm.vue
<template>
  <div>
    <form>
      <h2>Create a post:</h2>
      <div>
        <input
          placeholder="Hi World!"
          name="content"
          :value="modelValue"
          @change="$emit('update:modelValue', $event.target.value)"
        />
        <ErrorMessage :error="error" />
        <ElButton type="primary" color="teal" @click="$emit('submit-form')">
          Submit
        </ElButton>
      </div>
    </form>
    <ErrorMessage
      :error="error"
      :message="message"
    />
  </div>
</template>

<script>
import ErrorMessage from './ErrorMessage.vue';

export default {
  name: 'PostForm',
  props: {
    modelValue: String,
    error: Object,
  },
  computed: {
    errorMessage() {
      return this.error.graphQLErrors[0].message;
    },
  },
  emits: [
    'submit-form',
  ],
  components: { ErrorMessage },
};
</script>

<style>

</style>

// frontend/react-sample/src/components/common/PostForm.tsx
import React from 'react';
import { Button, Form } from 'semantic-ui-react';
import { PostFormProps } from './types';

const ErrorMessage = ({
  message
}: { message: string}) => (
  <div className="ui error message" style={{ marginBottom: 20 }}>
    <ul className="list">
      <li>{message}</li>
    </ul>
  </div>
);

const PostForm = ({
  error,
  inputValue,
  onChange,
  onSubmit,
}: PostFormProps) => {
  return (
    <>
      <Form onSubmit={onSubmit}>
        <h2>Create a post:</h2>
        <Form.Field>
          <Form.Input
            placeholder="Hi World!"
            name="content"
            onChange={onChange}
            value={inputValue}
            error={error ? true : false}
          />
          <Button type="submit" color="teal">
            Submit
          </Button>
        </Form.Field>
      </Form>
      {error && (
        <ErrorMessage 
          message={error.graphQLErrors[0].message} 
        />
      )}
    </>
  );
};

export default PostForm;
