// frontend/react-sample/src/components/common/DeleteButton.tsx
import React from 'react';
import { Button, Confirm, Icon } from 'semantic-ui-react';
import MyPopupWrapper from './MyPopupWrapper';
import { DeleteButtonProps } from './types';

const DeleteButton = ({
  commentId,
  isPopupOpen,
  onConfirmDelete,
  onOpenPopup,
}: DeleteButtonProps) => {
  const popupContent = 
    commentId ? 'Delete comment' : 'Delete post';
  
  return (
    <>
      <MyPopupWrapper content={popupContent}>
        <Button
          as="div"
          color="red"
          floated="right"
          onClick={onOpenPopup(true)}
        >
          <Icon name="trash" style={{ margin: 0 }} />
        </Button>
      </MyPopupWrapper>
      <Confirm
        open={isPopupOpen}
        onCancel={onOpenPopup(false)}
        onConfirm={onConfirmDelete}
      />
    </>
  );
};

export default DeleteButton;

// frontend/vue-sample/src/components/common/Buttons/DeleteButton.vue
<template>
  <div>
    <ElTooltip effect="dark" :content="toolTipContent" placement="right">
      <ElButton icon="el-icon-delete" @click="$emit('open-popup', true)" />
    </ElTooltip>
    <ConfirmPopup
      :isOpen="isPopupOpen"
      @closePopup="$emit('open-popup', false)"
      @confirm="$emit('confirm-delete')"
    >
      {{ confirmTitle }}
    </ConfirmPopup>
  </div>
</template>

<script>
import ConfirmPopup from './ConfirmPopup.vue';

export default {
  name: 'DeleteButton',
  props: {
    commentId: String,
    postId: String,
    isPopupOpen: Boolean,
  },
  emits: [
    'confirm-delete',
    'open-popup',
  ],
  data() {
    return ({
      confirmTitle: 'Are you sure delete?',
    });
  },
  computed: {
    toolTipContent() {
      return this.commentId ? 'Delete comment' : 'Delete post';
    },
  },
  components: {
    ConfirmPopup,
  },
};
</script>

<style>

</style>
