// frontend/react-sample/src/components/common/PostPart/PostContent.tsx
import React from 'react';
import moment from 'moment';
import { Button, Card, Icon, Label } from 'semantic-ui-react';
import LikeButtonContainer from '../../../containers/common/LikeButtonContainer';
import MyPopupWrapper from '../MyPopupWrapper';
import DeleteButtonContainer from '../../../containers/common/DeleteButtonContainer';
import { PostContentProps } from './types';

const PostContent = ({
  isThisUser, user, post, onDeleteCallback
}: PostContentProps) => {
  const {
    id: postId,
    username,
    createdAt,
    content,
    commentCount,
  } = post;

  return (
    <Card fluid>
      <Card.Content>
        <Card.Header>{username}</Card.Header>
        <Card.Meta>{moment(createdAt).fromNow()}</Card.Meta>
        <Card.Description>{content}</Card.Description>
      </Card.Content>
      <hr />
      <Card.Content extra>
        <LikeButtonContainer user={user} post={post} />
        <MyPopupWrapper content="Comment on post">
          <Button
            as="div"
            labelPosition="right"
            onClick={() => console.log('Comment on post')}
          >
            <Button basic color="blue">
              <Icon name="comments" />
            </Button>
            <Label basic color="blue" pointing="left">
              {commentCount}
            </Label>
          </Button>
        </MyPopupWrapper>
        {isThisUser && (
          <DeleteButtonContainer 
            postId={postId} 
            onDeleteCallback={onDeleteCallback} 
          />
        )}
      </Card.Content>
    </Card>
  );
};

export default PostContent;

// frontend/vue-sample/src/components/common/PostPart/PostContent.vue
<template>
  <ElCard fluid>
    <div>
      <div>{{ post.username }}</div>
      <div>{{ createdTimeFromNow }}</div>
      <div>{{ post.content }}</div>
    </div>
    <hr />
    <div extra>
      <LikeButtonContainer v-bind="$props" />
      <ElTooltip effect="dark" content="Comment on post" placement="top">
        <ElButton basic color="blue">
          <i class="el-icon-s-comment" />
          {{ post.commentCount }}
        </ElButton>
      </ElTooltip>
      <DeleteButtonContainer
        v-if="isThisUser"
        :postId="post.postId"
        @delete="$emit('delete-post')"
      />
    </div>
  </ElCard>
</template>

<script>
import { singlePostProps, userProps } from '@/types';

export default {
  name: 'PostContent',
  props: {
    isThisUser: Boolean,
    user: userProps,
    post: singlePostProps,
  },
  emits: [
    'delete-post',
  ],
  computed: {
    createdTimeFromNow() {
      return this.$store.getters.createdTimeFromNow()(this.post.createdAt);
    },
  },
};
</script>

<style>

</style>
