// frontend/vue-sample/src/components/common/PostPart/CommentItem.vue
<template>
  <div fluid key={comment.id}>
    <div>
      <DeleteButtonContainer
        v-if="isThisUserComment"
        :postId="postId"
        :commentId="comment.id"
      />
      <div>{{ comment.username }}</div>
      <div>{{ moment(comment.createdAt).fromNow() }}</div>
      <div>{{ comment.content }}</div>
    </div>
  </div>
</template>

<script>
import { singleCommentProps } from '@/types';

export default {
  name: 'CommentItem',
  props: {
    isThisUserComment: Boolean,
    postId: Number || String,
    comment: singleCommentProps,
  },
};
</script>

<style>

</style>

// frontend/react-sample/src/components/common/PostPart/CommentItem.tsx
import React from 'react';
import moment from 'moment';
import { Card } from 'semantic-ui-react';
import DeleteButtonContainer from '../../../containers/common/DeleteButtonContainer';
import { CommentItemProps } from './types';

const CommentItem = ({
  isThisUserComment, postId, comment
}: CommentItemProps) => {
  
  return (
    <Card fluid key={comment.id}>
      <Card.Content>
        {isThisUserComment && (
          <DeleteButtonContainer postId={postId} commentId={comment.id} />
        )}
        <Card.Header>{comment.username}</Card.Header>
        <Card.Meta>{moment(comment.createdAt).fromNow()}</Card.Meta>
        <Card.Description>{comment.content}</Card.Description>
      </Card.Content>
    </Card>
  );
};

export default CommentItem;
