// frontend/vue-sample/src/components/common/PostPart/PostCommentForm.vue
<template>
  <ElCard>
    <div>
      <h5>Post a comment</h5>
      <form>
        <div className="ui action input fluid">
          <input
            type="text"
            placeholder="Comment.."
            name="comment"
            :ref="commentInputRef"
            :value="modelValue"
            @change="$emit('update:modelValue', $event.target.value)"
          />
          <ElButton
            type="submit"
            :disabled="isCommentEmpty"
            @click="$emit('submit-comment')"
          >
            Submit
          </ElButton>
        </div>
      </form>
    </div>
  </ElCard>
</template>

<script>
export default {
  name: 'PostCommentForm',
  props: {
    commentInputRef: Object,
    modelValue: String,
  },
  emits: [
    'submit-comment',
  ],
};
</script>

<style>

</style>

// frontend/react-sample/src/components/common/PostPart/PostCommentForm.tsx
import React from 'react';
import { Card, Form } from 'semantic-ui-react';
import { PostCommentFormProps } from './types';

const PostCommentForm = ({
  commentInputRef, commentValue, onChange, onSubmit
}: PostCommentFormProps) => {
  const isCommentEmpty = commentValue.trim() === '';
  
  return (
    <Card fluid>
      <Card.Content>
        <h5>{'Post a comment'}</h5>
        <Form>
          <div className="ui action input fluid">
            <input
              type="text"
              placeholder="Comment.."
              name="comment"
              value={commentValue}
              onChange={onChange}
              ref={commentInputRef}
            />
            <button
              type="submit"
              className="ui button teal"
              disabled={isCommentEmpty}
              onClick={onSubmit}
            >
              {'Submit'}
            </button>
          </div>
        </Form>
      </Card.Content>
    </Card>
  );
};

export default PostCommentForm;
