// frontend/react-sample/src/components/common/LikeButton.tsx
import React from 'react';
import { Button, Icon, Label } from 'semantic-ui-react';
import { Link } from 'react-router-dom';
import { LikeButtonProps } from './types';
import MyPopupWrapper from './MyPopupWrapper';

const LikeButton = ({
  isLiked, 
  post: { likeCount, },
  user, 
  onLikePost,
}: LikeButtonProps) => {
  const likeButton = user ? (
    isLiked ? (
      <Button color="teal">
        <Icon name="heart" />
      </Button>
    ) : (
      <Button color="teal" basic>
        <Icon name="heart" />
      </Button>
    )
  ) : (
    <Button as={Link} to="/login" color="teal" basic>
      <Icon name="heart" />
    </Button>
  );

  const popupContent = isLiked ? 'Unlike' : 'Like';
  return (
    <Button as="div" labelPosition="right" onClick={onLikePost}>
      <MyPopupWrapper content={popupContent}>{likeButton}</MyPopupWrapper>
      <Label basic color="teal" pointing="left">
        {likeCount}
      </Label>
    </Button>
  );
};

export default LikeButton;

// frontend/vue-sample/src/components/common/LikeButton.vue
<template>
  <ElTooltip effect="dark" :content="toolTipContent" placement="right">
    <ElButton @click="handleLikePost">
        <i v-if="user && isLiked" class="el-icon-star-on" />
        <i v-else class="el-icon-star-off" />
      {{ post.likeCount || 0 }}
    </ElButton>
  </ElTooltip>
</template>

<script>
import { useRouter } from 'vue-router';

export default {
  name: 'LikeButton',
  setup() {
    const {
      push,
    } = useRouter();

    return ({ push });
  },
  props: {
    isLiked: Boolean,
    user: Object || null,
    post: Object,
  },
  computed: {
    toolTipContent() {
      return (this.isLiked && this.user) ? 'Unlike' : 'Like';
    },
  },
  emits: [
    'like-post',
  ],
  methods: {
    handleLikePost() {
      if (this.user) {
        this.$emit('like-post');
      } else {
        this.handleDirectToLogin();
      }
    },
    handleDirectToLogin() {
      this.push('/login');
    },
  },
};
</script>

<style>

</style>
